### ISSUE TITLE
Do you have any intention to support spigot 1.18.x?

### ISSUE THREAD

**Issue by QSlotus** [TechnicFox/EmojiesFox#5]
Hi. I found this plugin on modrinth and it really interested me. However, I found that it only supports 1.21.x :(

My server version is `Spigot 1.18.2` and I really want to add it to the server and use it with my friends.

I tried to make it support  1.18.2 myself but failed due to my low technical ability 😥

So I want to ask if you have any plans to support Spigot 1.18.2?

Thank you very much!

**Comment by TechnicFox** [comment]
Hey, I would like to help, but the problem is that to downgrade to 1.18 I will have to change how plugin works with items. Because of the changes in 1.20.5 where they changed NBT to item tags, and I have no time nor the motivation to do that. But you can always try for yourself. Note that files on github are newer and implements localization.

P.S.
Didn't Know that my plugin would be so popular that I would get suggestions
